project_two/app_two/urls.py
from django.urls import path
from . import views

# Template Tagging
app_name = 'app_two'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('relative/', views.relative, name='relative_urls'),
    # path('users/', views.users, name='users'),
    path('', views.index, name='index'),
    # path('form/', views.form_name_view, name='form_name'),
    path('login', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name="special")
]

project_two/project_two/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from app_two import views


urlpatterns = [
    path('', include('app_two.urls')),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

project_two/app_two/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    portforlio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=256, unique=True)

    def __str__(self):
        return self.top_name

class WebPage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    name = models.CharField(max_length=256, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage, on_delete=models.PROTECT)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

# class User(models.Model):
#     first_name = models.CharField(max_length=128)
#     last_name = models.CharField(max_length=128)
#     email = models.EmailField(max_length=256, unique=True)

project_two/app_two/forms.py
from django import forms
from django.core import validators
# from app_two.models import User
from django.contrib.auth.models import User
from app_two.models import UserProfileInfo

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to start with Z.")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portforlio_site', 'profile_pic')



class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

# class NewUser(forms.ModelForm):
#     class Meta():
#         model = User
#         fields = '__all__'

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("Gotcha Bot!")
    #     return botcatcher

project_two/app_two/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from app_two.models import AccessRecord, Topic, WebPage # ,User
# from app_two.forms import NewUser
# from . import forms
# Create your views here.
from app_two.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}

    return render(request, 'app_two/index.html', context=date_dict)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in.")

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user.form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'app_two/registration.html', {'user_form':user_form,
                                                         'profile_form':profile_form,
                                                         'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active.")

        else:
            print('Someone tried to log in and failed')
            print('Username: {}'.format(username))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'app_two/login.html', {})



# def form_name_view(request):
#     form = forms.FormName()
#
#     if request.method == 'POST':
#         form = forms.FormName(request.POST)
#
#         if form.is_valid():
#             print("Validation Success")
#             print("Name: "+form.cleaned_data['name'])
#             print("Email: "+form.cleaned_data['email'])
#             print("Text: "+form.cleaned_data['text'])
#
#     return render(request, 'app_two/form.html', {'form':form})
#
# def users(request):
#     user_list = User.objects.order_by('first_name')
#     users_dict = {"users":user_list}
#     return render(request, 'app_two/users.html', context=users_dict)
#     form = NewUser()
#     if request.method == 'POST':
#         form = NewUser(request.POST)
#         if form.is_valid():
#             form.save(commit=True)
#             return index(request)
#         else:
#             print("Error, Form invalid.")
#     return render(request, 'app_two/users.html', context={'form':form})

def relative(request):
    context_dict = {'text':'hello world', 'number':100}

    return render(request, 'app_two/relative_urls.html', context_dict)

project_two/templates/app_two/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li><a class="navbar-brand" href="{% url 'app_two:index' %}">Home</a></li>
          <li><a class="nav-link" href="{% url 'app_two:relative_urls' %}">Relative Urls</a></li>
          <li><a class="nav-link" href="{% url 'app_two:register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'app_two:user_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="nav-link" href="{% url 'app_two:user_login' %}">Login</a></li>
          {% endif %}
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">

      {% block body_block %}

      {% endblock %}

    </div>
  </body>
</html>

project_two/templates/app_two/form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <div class='container'>
      <h1>Fill out this form.</h1>
      <form method="POST"}>
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
  </body>
</html>

project_two/templates/app_two/index.html
<!-- <!DOCTYPE html> -->
{% extends "app_two/base.html" %}
{% block body_block %}

<!-- {% load staticfiles %}
 <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body> -->



    <h1>Django Level Two</h1>
    <h2>Access Records</h2>


    <div class=djangtwo>
      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
        {% for acc in access_records %}
        <tr>
          <td>{{ acc.name }}</td>
          <td>{{ acc.date }}</td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
        <p>No Access Records Found.</p>
      {% endif %}

{% endblock %}

  <!-- </body>
</html> -->

project_two/templates/app_two/login.html
{% extends 'app_two/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please log in:</h1>
  <form class="" action="{% url 'app_two:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">User Name:</label>
    <input type="text" name="username" placeholder="Username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>

</div>
{% endblock %}

project_two/templates/app_two/registration.html
{% extends 'app_two/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank You for registering.</h1>
  {% else %}
    <h1>Register Here.</h1>
    <h3>Fill out the form</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}

project_two/templates/app_two/relative_urls.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome to Relative Urls</title>
  </head>
  <body>
    <a href="{% url 'app_two:index' %}">Index Page</a>
    <a href="{% url 'admin:index' %}">Admin Page</a>

    <h1>{{ text|upper }}</h1>
    <h1>{{ number|add:"99" }}</h1>
  </body>
</html>

project_two/templates/app_two/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1>Please sign up here.</h1>
      <form method="POST">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>

  </body>
</html>